# Generated by Django 5.2.17 on 2026-09-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='files',
            field=models.JSONField(blank=True, default=dict, help_text="Submitted multi-file repository map (e.g. {'app/calculator.py': '...'})."),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
