# Generated by Django 5.2.17 on 2026-09-01 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('tests_total', models.PositiveIntegerField(default=0)),
                ('tests_passed', models.PositiveIntegerField(default=0)),
                ('tests_failed', models.PositiveIntegerField(default=0)),
                ('execution_time', models.FloatField(default=0, help_text='Execution time in seconds.')),
                ('memory_used', models.FloatField(default=0, help_text='Memory used in MB.')),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='submissions.submission')),
            ],
        ),
    ]
