# Generated by Django 5.2.17 on 2026-09-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TRAINER', 'Trainer'), ('ADMIN', 'Admin'), ('RECRUITER', 'Recruiter')], default='STUDENT', max_length=20),
        ),
    ]
