# Generated by Django 5.2.17 on 2026-09-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20)),
                ('challenge_type', models.CharField(choices=[('BUG_FIX', 'Bug Fix'), ('FEATURE', 'Feature'), ('API', 'API Integration'), ('DATABASE', 'Database'), ('PERFORMANCE', 'Performance'), ('SECURITY', 'Security'), ('TESTING', 'Testing'), ('CODE_REVIEW', 'Code Review'), ('DEBUGGING', 'Debugging')], default='BUG_FIX', max_length=20)),
                ('programming_language', models.CharField(default='Python', max_length=50)),
                ('starter_code', models.TextField(blank=True)),
                ('time_limit', models.PositiveIntegerField(default=10, help_text='Maximum execution time in seconds.')),
                ('memory_limit', models.PositiveIntegerField(default=256, help_text='Maximum memory in MB.')),
                ('points', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
