# Generated by Django 5.2.17 on 2026-09-01 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text="Relative repository file path (e.g., 'src/main.py', 'README.md').", max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('is_test', models.BooleanField(default=False, help_text='Identifies whether this file is a test file.')),
                ('is_readonly', models.BooleanField(default=False, help_text='Identifies whether this file is read-only for students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='challenges.challenge')),
            ],
            options={
                'ordering': ['path'],
                'unique_together': {('challenge', 'path')},
            },
        ),
    ]
