# Generated by Django 5.2.17 on 2026-09-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challengefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='entrypoint',
            field=models.CharField(blank=True, default='', help_text="Relative entrypoint file path for repository challenges (e.g. 'app/calculator.py').", max_length=255),
        ),
    ]
