# Generated by Django on 2026-09-03
from django.db import migrations


SEED_ACHIEVEMENTS = [
    {
        "code": "BUG_SLAYER",
        "name": "Bug Slayer",
        "description": "Passed 3 Bug Fix challenges.",
        "icon": "🐛",
        "requirement_type": "BUG_FIX_COUNT",
        "requirement_value": 3,
    },
    {
        "code": "SECURITY_HUNTER",
        "name": "Security Hunter",
        "description": "Passed 3 Security challenges.",
        "icon": "🛡️",
        "requirement_type": "SECURITY_COUNT",
        "requirement_value": 3,
    },
    {
        "code": "PERFORMANCE_ENGINEER",
        "name": "Performance Engineer",
        "description": "Passed 3 Performance challenges.",
        "icon": "⚡",
        "requirement_type": "PERFORMANCE_COUNT",
        "requirement_value": 3,
    },
    {
        "code": "TEST_MASTER",
        "name": "Test Master",
        "description": "Passed 3 Testing challenges.",
        "icon": "🧪",
        "requirement_type": "TESTING_COUNT",
        "requirement_value": 3,
    },
    {
        "code": "PERFECT_RUN",
        "name": "Perfect Run",
        "description": "Achieved 100/100 on 5 distinct challenges.",
        "icon": "🎯",
        "requirement_type": "PERFECT_SCORE_COUNT",
        "requirement_value": 5,
    },
    {
        "code": "DEVFORGE_VETERAN",
        "name": "DevForge Veteran",
        "description": "Completed 10 distinct challenges.",
        "icon": "🎖️",
        "requirement_type": "TOTAL_COMPLETED_COUNT",
        "requirement_value": 10,
    },
]


def seed_achievements(apps, schema_editor):
    Achievement = apps.get_model("evaluations", "Achievement")
    for ach in SEED_ACHIEVEMENTS:
        Achievement.objects.update_or_create(
            code=ach["code"],
            defaults={
                "name": ach["name"],
                "description": ach["description"],
                "icon": ach["icon"],
                "requirement_type": ach["requirement_type"],
                "requirement_value": ach["requirement_value"],
                "is_active": True,
            },
        )


def reverse_seed(apps, schema_editor):
    Achievement = apps.get_model("evaluations", "Achievement")
    codes = [ach["code"] for ach in SEED_ACHIEVEMENTS]
    Achievement.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0004_achievement_userachievement"),
    ]

    operations = [
        migrations.RunPython(seed_achievements, reverse_seed),
    ]
